### ISSUE TITLE
Oracle DB

### ISSUE THREAD

**Issue by mcdir** [babelouest/hoel#14]
Hi there. 
Do you think to implement support Oracle DB?
Is it possible? Have you any plan for this.

**Comment by babelouest** [comment]
Hello @mcdir ,

Sorry, I don't plan to support Oracle DB on Hoel for now, nor other relational databases like Microsoft SQLServer or IBM DB2.
The main reasons are:
- I don't use them and I don't have the need for my personal use
- I don't know if there are `"free as in free speech"` client libraries for those Databases

Concerning Oracle, I noticed [Oracle Instant Client](https://www.oracle.com/technetwork/database/database-technologies/instant-client/overview/index.html) for Linux, which comes with a client library, but its license is [non-free](https://www.oracle.com/technetwork/licenses/instant-client-lic-152016.html) (as in free speech). Therefore I will not use it to connect Hoel to Oracle DB.

But if you want to, you can create yourself a new connector for Oracle DB with Hoel.
You can get the inspiration from the existing connectors, like MariaDB, SQLite3 or PostgreSQL.

The steps to follow are:

1- Create a new [HOEL_DB_TYPE](https://github.com/babelouest/hoel/blob/master/include/hoel.h#L41), like `HOEL_DB_TYPE_ORACLE`.

2- Implement the following functions in a dedicated source file, like the [MariaDB implementation](https://github.com/babelouest/hoel/blob/master/src/hoel-mariadb.c):

```C
struct _h_connection * h_connect_oracle(<your parameters>);
void h_close_oracle(struct _h_connection * conn);
char * h_escape_string_oracle(const struct _h_connection * conn, const char * unsafe);
int h_last_insert_id_oracle(const struct _h_connection * conn);
int h_select_query_oracle(const struct _h_connection * conn, const char * query, struct _h_result * result);
int h_exec_query_oracle(const struct _h_connection * conn, const char * query);
int h_execute_query_json_oracle(const struct _h_connection * conn, const char * query, json_t ** j_result)
```

3- Connect those functions to Hoel core functions:
https://github.com/babelouest/hoel/blob/master/src/hoel.c#L40
https://github.com/babelouest/hoel/blob/master/src/hoel.c#L72
https://github.com/babelouest/hoel/blob/master/src/hoel.c#L106
https://github.com/babelouest/hoel/blob/master/src/hoel.c#L141
https://github.com/babelouest/hoel/blob/master/src/hoel.c#L292

4- Adapt the [Makefile](https://github.com/babelouest/hoel/blob/master/src/Makefile) or the [CMakeLists.txt](https://github.com/babelouest/hoel/blob/master/CMakeLists.txt)

That should do it.

**Comment by mcdir** [comment]
@babelouest  Thanks a lot for the extended answer.
