### ISSUE TITLE
Use libmariadb-dev instead of libmariadbclient-dev

### ISSUE THREAD

**Issue by ottok** [babelouest/hoel#19]
Hello!

Your current README/CI uses libmariadbclient-dev. This is fine for now, but in the future when you update the Debian/Ubuntu version you are using in the CI, you should change those to libmariadb-dev (or libmariadb-dev-compat if you need to build something old that does not find the correct soname otherwise).

https://github.com/babelouest/hoel/search?q=libmariadbclient-dev

**Comment by babelouest** [comment]
Hello @ottok ,

Thanks for the reminder, I don't go often in this documentation.
