### ISSUE TITLE
orcania library required to build hoel database library

### ISSUE THREAD

**Issue by harihanv** [babelouest/hoel#2]
hoel-Wiki needs to be updated to include build instructions for orcania library.

**Comment by harihanv** [comment]
PREFIX ?=/usr/local
install: all
        install -d ${PREFIX}/lib
        cp $(OUTPUT).$(VERSION) $(PREFIX)/lib
        install -d ${PREFIX}/include
        cp orcania.h $(PREFIX)/include
        /sbin/ldconfig -r $(PREFIX)

orcania library changes in Makefile to  install in other directories

**Comment by harihanv** [comment]
cd ./examples && make example_sqlite3
make[1]: Entering directory `/home/harish/newgatewaysrc/3rdparty/hoel/examples'
gcc -c -c -Wall -D_REENTRANT -I/home/harish/newgatewaysrc/3rdparty/install/include -O3 example_sqlite3.c
gcc -o example_sqlite3 example_sqlite3.o -lc -lhoel -ljansson -lyder -lorcania -L/home/harish/newgatewaysrc/3rdparty/install/lib -L../src
../src/libhoel.so: undefined reference to `json_stringn'
collect2: error: ld returned 1 exit status
make[1]: *** [example_sqlite3] Error 1
make[1]: Leaving directory `/home/harish/newgatewaysrc/3rdparty/hoel/examples'
make: *** [example_sqlite3] Error 2

**Comment by babelouest** [comment]
You're right, documentation has been [updated](https://github.com/babelouest/hoel/commit/53d5b51af8ef5dca4222119984aa4702478dcbd2), thanks.

**Comment by harihanv** [comment]
Thanks for acknowledging.  I want to test,  kindly let me know if you have
document to understand the project

**Comment by babelouest** [comment]
Thanks for testing, the documentation available is in the `README.md` file and you can find some examples in the `example` folder with all the functionalities.
If you want more large examples on how it's used, you can check the source code of my other projects, like angharad or glewlwyd.

**Comment by babelouest** [comment]
Let me know if some functionalities are not clear or buggy

**Comment by harihanv** [comment]
I am in the process of fixing json_stringn function not found issue
