### ISSUE TITLE
Question regarding support for new databases

### ISSUE THREAD

**Issue by silvioprog** [babelouest/hoel#3]
Hello,

Firstly, thanks for this great job.

I have a silly question. Does hoel have plan to support new databases (e.g: https://firebirdsql.org)?

Thank you!

**Comment by babelouest** [comment]
Hi Silvio,

Right now I don't have plans to support other databases, I'm good with MySQL/MariaDB and SQLite.

Contributions are more than welcome though. It shouldn't be that hard if you know the underlying API for the new database and get inspiration from the existing databases supported.

As long as it's a SQL database, the SQL query generation should require minimal changes.
- Create a `h_connect_*` and `h_close_*` functions that connects and closes the database using a `struct _h_connection *` object and update [h_close_db](https://github.com/babelouest/hoel/blob/master/src/hoel.c#L34) to simplify closing a connection.
- Create a `h_escape_string_*` function and update [h_escape_string](https://github.com/babelouest/hoel/blob/master/src/hoel.c#L66)
- Create a `h_execute_query_*` function and update [h_execute_query](https://github.com/babelouest/hoel/blob/master/src/hoel.c#L100)
- Create a `h_execute_query_json_*` function and update [h_execute_query_json](https://github.com/babelouest/hoel/blob/master/src/hoel.c#L133)
- Create a `h_last_insert_id_*` function and update [h_last_insert_id](https://github.com/babelouest/hoel/blob/master/src/hoel.c#L283)
- The longest part should be the result parser for `select` queries, where you loop into the result table, and fill in the json object or the `struct _h_result`.
Check the functions [h_execute_query_json_mariadb](https://github.com/babelouest/hoel/blob/master/src/hoel-mariadb.c#L212) and [h_execute_query_mariadb](https://github.com/babelouest/hoel/blob/master/src/hoel-mariadb.c#L143) to see how I do it for MariaDB.
