### ISSUE TITLE
[SMALL FEATURE] static site

### ISSUE THREAD

**Issue by silvioprog** [babelouest/hoel#7]
Hi dudes.

Please create the GIthub-style static site ([something like that](https://babelouest.github.io/glewlwyd)) of Hoel project.

Thank you!

**Comment by babelouest** [comment]
Like that: [https://babelouest.github.io/hoel/](https://babelouest.github.io/hoel/)? No problem ;)

**Comment by silvioprog** [comment]
Wooow, so fast. :flushed: :flushed: :flushed:

Thanks dude, you are the guy! :+1:

**Comment by babelouest** [comment]
Actually it's just a `click-click-click` process on the config page of the github project, it simply takes the `README.md` file, build an html page and add a css, very easy and when you change the `README.md`, it changes automatically the static site.

Thanks to github, not me ;)
